### ISSUE TITLE
Question: When does the init-container/helm-deploy.sh get executed

### ISSUE THREAD

**Issue by NaraVen** [micya/aks-arm#1]
When does the code in the init-container get executed? Is the container image specified in the init-container-deploy.json ( "image": "ghcr.io/micya/init-container") built from the init-container Dockerfile?

**Comment by micya** [comment]
That's correct. I would note that if you do not need to use ARM templates, you might want to consider using Terraform as it supports installing helm charts (without jumping through hoops like deploying ACI as shown here).

**Comment by NaraVen** [comment]
Thank you for the reply.
